# Generated by Django 5.1.1 on 2024-09-04 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['-id'], 'verbose_name': 'todo', 'verbose_name_plural': 'todos'},
        ),
        migrations.AlterModelTable(
            name='todo',
            table='todo',
        ),
    ]
